"""New Migration

Revision ID: 275bc47a7fe3
Revises: 
Create Date: 2023-06-17 13:36:36.549937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275bc47a7fe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countrylist',
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('checklist', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('other_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('passport_number', sa.String(length=255), nullable=True),
    sa.Column('national_identification_number', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_clerk', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_a_admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('checklist',
    sa.Column('checklist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('dateofoccurence', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('helthfacility', sa.String(length=100), nullable=True),
    sa.Column('doctor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('checklist_id', 'subject')
    )
    op.create_table('checkpoint',
    sa.Column('checkpoint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('dateofoccurence', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('officer', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['officer'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('checkpoint_id', 'officer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoint')
    op.drop_table('checklist')
    op.drop_table('user')
    op.drop_table('countrylist')
    # ### end Alembic commands ###
